// Build script: reads crawled product/category JSON (from scripts/data/) and
// generates src/data/catalog.ts with all categories and products.
// Usage: node scripts/build-catalog.mjs

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const CATEGORIES_JSON = 'scripts/data/crawled-categories.json';
const PRODUCTS_JSON = 'scripts/data/crawled-products.json';
const HOME_GRIDS_JSON = 'scripts/data/home-grids.json';

const categories = JSON.parse(readFileSync(CATEGORIES_JSON, 'utf8'));
const rawProducts = JSON.parse(readFileSync(PRODUCTS_JSON, 'utf8'));

// ---- build product list ---------------------------------------------------
// Keep EVERY category listing, in crawl order. The original site lists products
// in page order (page 1 first, then page 2…), so crawl order == original order.
// A product may appear in several categories; each appearance is kept so every
// category page shows the exact same products, in the same order, as the original.
const products = rawProducts.map((p, i) => {
  // Placeholder price — replace with real price list before launch
  const price = Number(((i % 8) * 1.5 + 7.99).toFixed(2));
  const desc =
    `${p.name}<br/>Premium quality wholesale item.<br/>One size fits most.<br/>` +
    `Available in assorted colors and styles.`;
  return {
    slug: p.slug,
    name: p.name,
    category: p.category,
    price,
    compareAtPrice: null,
    image: p.image,
    description: desc,
  };
});

// Taglines for categories (generic for the many new ones)
const taglines = {
  'cc-beanie': 'Winter beanies in every style — pom, cuff, sequin, letter and more.',
  'cc-scarf': 'Infinity, oblong and satin scarves for wholesale and retail.',
  'cc-gloves': 'Touchscreen, padded-cuff and knit winter gloves, by the dozen.',
  'cc-cap': 'Trucker, snapback and baseball caps with letter embroidery.',
  'new': 'Fresh arrivals added regularly.',
  'sale': 'Discounted items — while stock lasts.',
};

const enrichedCategories = categories.map((c) => ({
  slug: c.slug,
  name: c.name,
  tagline: taglines[c.slug] || `Shop ${c.name.toLowerCase()} at wholesale prices.`,
  image: c.image || products.find((p) => p.category === c.slug)?.image || '',
}));

// The C.C umbrella category has no products of its own — reuse the beanie image.
const cc = enrichedCategories.find((c) => c.slug === 'cc');
if (cc && !cc.image) {
  cc.image = enrichedCategories.find((c) => c.slug === 'cc-beanie')?.image || '';
}

// Homepage product grids as they appear on the original site.
let homeGrids = { featured: [], popular: [], new: [] };
try {
  homeGrids = JSON.parse(readFileSync(HOME_GRIDS_JSON, 'utf8'));
} catch {
  // optional
}

// ---- emit catalog.ts ------------------------------------------------------
const catJson = JSON.stringify(enrichedCategories, null, 1);
const prodJson = JSON.stringify(products, null, 1);

const out = `// AUTO-GENERATED by scripts/build-catalog.mjs from scripts/data/crawled-*.json
// Do not edit by hand. Re-run \`node scripts/build-catalog.mjs\` after re-crawling.
//
// ⚠️  PLACEHOLDER PRICES: every \`price\` below is a stand-in. Replace them
// with the real price list before launch (the cart totals use these values).

export interface Category {
  slug: string;
  name: string;
  tagline: string;
  image: string;
}

export interface Product {
  slug: string;
  name: string;
  category: string;
  price: number;
  compareAtPrice: number | null;
  image: string;
  description: string;
}

export const categories: Category[] = ${catJson};

export const products: Product[] = ${prodJson};

export const getCategory = (slug: string) => categories.find((c) => c.slug === slug);

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);

export const productsByCategory = (slug: string) => {
  const list =
    slug === 'cc'
      ? products.filter((p) => p.category === 'cc' || p.category.startsWith('cc-'))
      : products.filter((p) => p.category === slug);
  // The cc umbrella unions several categories — drop cross-category duplicates.
  const seen = new Set<string>();
  return list.filter((p) => (seen.has(p.slug) ? false : (seen.add(p.slug), true)));
};

export const featuredProducts = products.slice(0, 12);

export const homeSections = {
  featured: ${JSON.stringify(homeGrids.featured)},
  popular: ${JSON.stringify(homeGrids.popular)},
  new: ${JSON.stringify(homeGrids.new)},
};
`;

mkdirSync('src/data', { recursive: true });
writeFileSync('src/data/catalog.ts', out);
console.log(`wrote src/data/catalog.ts: ${products.length} products, ${enrichedCategories.length} categories`);